#pragma once

enum gbma_prot_cmd {
    GBRIDGE_PROT_MA_CMD_OPEN,
    GBRIDGE_PROT_MA_CMD_CLOSE,
    GBRIDGE_PROT_MA_CMD_CONNECT,
    GBRIDGE_PROT_MA_CMD_LISTEN,
    GBRIDGE_PROT_MA_CMD_ACCEPT,
    GBRIDGE_PROT_MA_CMD_SEND,
    GBRIDGE_PROT_MA_CMD_RECV
};
